### ISSUE TITLE
BlackScreen after playback

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#229] opened 2023-09-08 13:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1 - Open the Android App
2 - Play video
3 - Leave playback going LONG enough (about 10/12 mins)
4 - All of a sudden would getting a blank screen, however all playback control, subtitles, and Sound would be working fine.

Video Evidence

https://drive.google.com/file/d/1td7_qJb9Gus-H8m5Tm25ZEQitzlymEkK/viewsubtitles

### Expected Behavior

Actual result: All playback control, subtitle, Sound starts but video doesn’t, only a blank screen.
Expected result: All player control functionalities and video should play.

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.9.1

### Device

Device: Samsung Galaxy Tab A7 
Android version: 12
VPN: Nordlayer 
Region: France

### Additional information / Code snippets / Screenshots

Additional information

BITMOVIN_PLAYER_CSS=https://stagev2-app-assets.britbox.takeoffmedia.com/player/v8/css/bitmovinplayer-ui.min.css
BITMOVIN_PLAYER_JS=https://stagev2-app-assets.britbox.takeoffmedia.com/player/v8/js/bitmovinplayer-ui.min.js

**Comment by AngeloFragliassoBritBox** [comment] 2023-09-08 13:57
Details about where it's been reproduced:

Device: Samsung Galaxy Tab A7 
Android version: 12

VPN : Nordlayer 
Region : France 

How to Repro?

Play episode up to 10-12 min

**Comment by jamesdavidholding** [comment] 2023-09-08 14:45
Hi - I am just sharing this information with the team to go and try and replicate the issue. 

Could i ask you to reshare the video please mention at the top of the ticket, it does not open for me. 
<img width="839" alt="image" src="https://github.com/bitmovin/bitmovin-player-react-native/assets/62567238/1537cf7c-e431-44c1-b5f0-254ed3682c8e">

Also can I ask 
- Does this happen for all content or just some? ie. the one you have noticed 
- have you identified this being specific to device and OS or does that not seem to matter form your attempts to replicate this

**Comment by jonathanm-tkf** [comment] 2023-09-08 14:49
hi @jamesdavidholding https://drive.google.com/file/d/1td7_qJb9Gus-H8m5Tm25ZEQitzlymEkK/view?usp=sharing

**Comment by jonathanm-tkf** [comment] 2023-09-08 14:52
I will now respond to your queries:

1 - We assume it happens with any type of content, because many users are reporting the same scenario.

2- I didn't understand the question it is detailed in the issue, it refers to 

Device: Samsung Galaxy Tab A7
Android version: 12

VPN : Nordlayer
Region : France

**Comment by jonathanm-tkf** [comment] 2023-09-12 12:16
Hi @team any updates for this issue?

cc: @jamesdavidholding, @AngeloFragliassoBritBox

**Comment by jamesdavidholding** [comment] 2023-09-12 13:18
Hi @jonathanm-tkf, thanks for providing the additional information. I have asked engineering to review your reply and feedback. 

Thanks 

James

**Comment by anujavagh** [comment] 2023-09-19 11:58
@jonathanm-tkf do you have the analytics sessions where this issue is still occuring please?

**Comment by LudoMichaud** [comment] 2023-10-02 16:03
@AngeloFragliassoBritBox I have not been able to pin point the specific Analytics sessions involved. If you could share the session ID, or link to the detailed view in the Dashboard, it would be helpful. 

Example : https://dashboard.bitmovin.com/analytics/sessions/695926bd-415c-49da-be82-0a29b7d690fa?from=1693558800000&licenseKey=69bab32b-7905-4aa2-ae25-06edb1ebf460&to=1693565940000&orgId=f47c7ba3-4732-469c-9bd2-d3adf4aa4d14&userId=9f58774d-c8c2-4f55-a8ca-aef0ebf85a98

Here *695926bd-415c-49da-be82-0a29b7d690fa* is the session ID of the above. 

Your Analytics is configured in GMT. This can be changed if needed.

If you can also share the Stream URL to reproduce the behaviour, it would be helpful

**Comment by AngeloFragliassoBritBox** [comment] 2023-10-04 08:50
Hi @LudoMichaud session id: A3507588-28F2-4294-A1D6-94EBAD60268B

Let me know if you need anything else.
Thanks,
Angelo.

**Comment by LudoMichaud** [comment] 2023-10-04 13:33
Thanks @AngeloFragliassoBritBox 
session link for my records : [[LINK]](https://dashboard.bitmovin.com/analytics/sessions/a3507588-28f2-4294-a1d6-94ebad60268b?infoTabId=1&licenseKey=69bab32b-7905-4aa2-ae25-06edb1ebf460&quickInterval=LAST_THREE_HOURS&orgId=f47c7ba3-4732-469c-9bd2-d3adf4aa4d14&userId=9f58774d-c8c2-4f55-a8ca-aef0ebf85a98)

On that session, it looks like the player didn't play at all, or only for 0.08s

If you could share a stream as well as what we need to reproduce the issue, it would be the best next steps.

**Comment by anujavagh** [comment] 2023-10-05 15:46
Closing for now as not many reports once launched with the new RN player

**Closed** 2023-10-06 11:57 UTC
