### ISSUE TITLE
pip(Picture in Picture) React native android is not working properly

### ISSUE THREAD

**Issue by iyyappanrock535** [bitmovin/bitmovin-player-react-native#202] opened 2023-08-21 20:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using bitmovin-player-react-native@0.7.2 version. The problem is i'm using two screens one for the list and another screen bitmovin-player component. So i have enabled pip(Picture in Picture) feature. It's working good but problem is
1. open list screen and go to bitmovin-player component screen
2. again back list screen and close the app but pip still showing that screen. 

so that is wrong, Pip only work bitmovin-player component screen. But pip is working all screens in react native android

Also I have tried this functions:
player.destory();

It's not working.
![WhatsApp Image 2023-08-19 at 11 03 34 PM](https://github.com/bitmovin/bitmovin-player-react-native/assets/84359596/60ed5d5d-e075-4774-ad60-82acfd53988c)

### Expected Behavior

So i want only pip work in only bitmovin-player component screen. Other screens disbale. 

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.2

### Device

Android

### Environment

React native:0.72.3

**Comment by christophaigner** [comment] 2023-08-31 08:29
Hi @iyyappanrock535,

Thank you for taking the time to report this issue.

Could you please provide us with a sample project to help us reproduce this issue?
Also, please provide as many details as possible, especially clear steps to reproduce and a screen recording would be great.

We're excited about supporting you in getting started with Bitmovin on React Native!

Thanks,
Chris

**Comment by jamesdavidholding** [comment] 2023-10-02 13:23
Hi @iyyappanrock535  Would you be able to assist with [some further information ](https://github.com/bitmovin/bitmovin-player-react-native/issues/202#issuecomment-1700593420)on this reported issue?

Many thanks 

James

**Comment by jamesdavidholding** [comment] 2023-10-12 08:35
Hi @iyyappanrock535

Since we haven’t heard back from you on this ticket after a few reminders, we will automatically close it for now. If this topic is still relevant to you, please feel free to raise a new ticket through your bitmovin support dashboard, where we’ll be glad to continue assisting you.

Please note the issues tab of this repository is being retired at the end of this month, enabling customers to raise tickets more swiftly and directly to customer support.

Best regards,

James

**Closed by jamesdavidholding** 2023-10-12 08:35 UTC
Labels: Pending feedback

**Comment by zigavehovec** [comment] 2024-04-08 14:39
Hi!
Version `0.21.0` with a fix for this issue has just been released: [Release v0.21.0 · bitmovin/bitmovin-player-react-native · GitHub](https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.21.0)
