### ISSUE TITLE
Problem with Android Subtitule custom label

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#150] opened 2023-07-03 20:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone I wanted to report a possible bug in the Android integration, this does not happen in iOS I attach evidence of both platforms.

iOS

![Simulator Screen Shot - iPhone 11 Pro Max - 2023-07-03 at 16 57 05](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/671a40c5-00a1-4190-882f-5c10674ad787)

Android

![image](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/4b41ce5f-5142-4eee-b61e-945ddb3b4c23)

### Expected Behavior

Android

![image](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/b5dce045-b33c-46d1-844a-5352ffc42b7d)

### Steps To Reproduce

1- Install the example
2- Run Subtitles and Captions screen
3- Press on options and try to change subtitles

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.2

**Comment by jonathanm-tkf** [comment] 2023-07-03 20:06
Hello guys 

I create this [PR](#151 ) and tried to solve the issue, can you check if the implementation it's ok?

**Comment by jonathanm-tkf** [comment] 2023-07-03 20:10
The only thing I couldn't solve was the CammelCase, probably something in the skin that is modified by custom CSS.

custom english => Custom English

**Comment by zigavehovec** [comment] 2023-07-07 07:28
Hi @jonathanm-tkf! 

Thanks for reporting this issue!
I've looked into this and the issue actually originates in the native SDK side and not in the React Native wrapper.
I've created an internal ticket and we will look into it.

We'll post an update when the issue is fixed here.

**Comment by jonathanm-tkf** [comment] 2023-08-02 14:10
Hi @zigavehovec and team 

can you confirm if this issue has any update from the native side?

I was checking the release list but I don't see anything regarding this issue.

https://developer.bitmovin.com/playback/docs/release-notes-android

Thanks and regards

**Comment by christophaigner** [comment] 2023-08-03 06:59
Hi @jonathanm-tkf,

Thanks again for reporting.
You're right, there is no update on this yet in our release notes, as this is scheduled for later in this quarter.

We will make sure to notify you here.

Chris

**Comment by AngeloFragliassoBritBox** [comment] 2023-09-21 14:38
Hi @christophaigner any news on this ticket please?
Thanks,
Angelo.

**Comment by coloradude** [comment] 2023-09-26 06:12
Hi @AngeloFragliassoBritBox, currently an internal ticket has been created and we are awaiting prioritization. We will let you know as soon as work has begun on the ticket. 
Best,
Stephen

**Comment by jamesdavidholding** [comment] 2023-10-02 12:02
For tracking purposes, the related engineering ticket ID is PA-2021

Can I confirm the user impact here is that on Android, it is a different experience than that which occurs on IOS and also, the UX/UI experience is impacted as the Label for some tracks is not displayed. Only the language identifier will be displayed.

**Comment by christophaigner** [comment] 2024-03-07 14:23
Fixed in version [v0.15.0](https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.15.0).

**Closed by christophaigner** 2024-03-07 14:23 UTC
Labels: bug, On Hold
