### ISSUE TITLE
Add Custom Html Ui by bitmovin-ui implementation

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#12] opened 2022-07-26 21:16 UTC
Hi, I have tried to implement first in ios, then I would go for android the implementation of Custom Html Ui, but I ran into a couple of problems and would like to know if you can help me better understand the code.

![image](https://user-images.githubusercontent.com/67608970/181111928-af0502f7-fb07-4a9b-8ab3-fdccf31abaa6.png)

![image](https://user-images.githubusercontent.com/67608970/181111790-9eb4b17b-6b4a-4be4-906c-e5751c17b7a3.png)

### Requirement

To implement both CSS and JS from the react-native side implementing events when the user performs a certain action on the skin e.g. close button etc.

#### Expectation to have both synchronous and asynchronous events 

```jsx
const player = usePlayer({
    styleConfig: {
      playerUiCss:
        'https://cdn.statically.io/gh/bitmovin/bitmovin-player-ios-samples/main/CustomHtmlUi/Supporting%20Files/bitmovinplayer-ui.min.css',
      playerUiJs:
        'https://cdn.statically.io/gh/bitmovin/bitmovin-player-ios-samples/main/CustomHtmlUi/Supporting%20Files/bitmovinplayer-ui.min.js',
    },
  });

 const onReceivedAsynchronousMessage = useCallback(
    (event: ReceivedAsynchronousMessage) => {
      prettyPrint(`MESSAGE [${event.message}]`, event);
    },
    []
  );

  const onReceivedSynchronousMessage = useCallback(
    (event: ReceivedSynchronousMessage) => {
      prettyPrint(`MESSAGE [${event.message}]`, event);
    },
    []
  );

  <PlayerView
      player={player}
      style={styles.player}
      onPlay={onEvent}
      onPlaying={onEvent}
      onPaused={onEvent}
      onReady={onReady}
      onSourceLoaded={onSourceLoaded}
      onReceivedAsynchronousMessage={onReceivedAsynchronousMessage} // new custom property method
      onReceivedSynchronousMessage={onReceivedSynchronousMessage} // new custom property method
    />
```

### Whtas it's the problem 

I am currently unable to call the events declared in the `RCTViewManager` as are 

```
RCT_EXPORT_VIEW_PROPERTY(onReceivedSynchronousMessage, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onReceivedAsynchronousMessage, RCTBubblingEventBlock)
```

I leave the reference commit in the fork I currently have 

[https://github.com/take0ffmedia/bitmovin-player-react-native/commit/a33b16b859a3bdb3206121ea85abadefdbe17838](https://github.com/take0ffmedia/bitmovin-player-react-native/commit/a33b16b859a3bdb3206121ea85abadefdbe17838)

if you can guide me on how to solve this problem I would appreciate it, in order to improve the code or solve it in the most efficient way as always thank you very much.

**Comment by jonathanm-tkf** [comment] 2022-07-26 21:19
@pogist 

I did not want to make a PR because there is still a long way to go, thank you very much.

**Comment by pogist** [comment] 2022-08-11 18:22
Hi @jonathanm-tkf, thank you very much for submitting this feature request. I will take a careful look at your code later, but I already spotted some issues with it. But I think it'd be better to suggest fixes for it in a pull request. Please, feel free to open one. And if you think there's still a lot to work on, just create it as a draft and then open it up for reviews when you consider it ready.

Now regarding your question about the events on iOS, the problem is that `PlayerModule` should not be the delegate for the `CustomMessageHandler`, but the `RNPlayerView` instance instead.

All the custom bubbling events are declared in the context of an `RNPlayerView` which is the native iOS `UIView` wrapping bitmovin's `PlayerView`. See these events for example https://github.com/bitmovin/bitmovin-player-react-native/blob/development/ios/RNPlayerView.swift#L6.

Just define the bubbling event properties in the `RNPlayerView` class, make it the delegate object for `CustomMessageHandler` and call them on their appropriate delegate methods.

```swift
// RNPlayerView.swift
@objc(RNPlayerView)
class RNPlayerView: UIView {
  // ...
  @objc var onReceivedSynchronousMessage: RCTBubblingEventBlock?
  @objc var onReceivedAsynchronousMessage: RCTBubblingEventBlock?
  var messageHandler: CustomMessageHandler?
  var userInterfaceConfig: BitmovinUserInterfaceConfig?

  func enableCustomUI() {
    // You may want to add some nil checks here, but I omitted those for the sake of example.
    messageHandler = CustomMessageHandler()
    messageHandler?.delegate = self
    userInterfaceConfig = BitmovinUserInterfaceConfig()
    userInterfaceConfig?.customMessageHandler = messageHandler
  }
  // ...
}

// RNPlayerView+CustomMessageHandlerDelegate.swift
extension RNPlayerView: CustomMessageHandlerDelegate {
  func receivedSynchronousMessage(_ message: String, withData data: String?) -> String? {
    onReceivedSynchronousMessage?(["message": message, "data": data])
  }

  func receivedAsynchronousMessage(_ message: String, withData data: String?) -> String? {
    onReceivedAsynchronousMessage?(["message": message, "data": data])
  }
}

// PlayerModule.swift
@objc(PlayerModule)
class PlayerModule: NSObject, RCTBridgeModule {
  // ...
  @objc(initWithConfig:config:)
  func initWithConfig(_ nativeId: NativeId, config: Any?) {
      bridge.uiManager.addUIBlock { [weak self] _, viewsRegistry in
          guard
              self?.players[nativeId] == nil,
              let playerConfig = RCTConvert.playerConfig(config)
          else {
              return
          }
          if let json = config as [String: Any]?, json["styleConfig"] != nil {
            if let playerView = viewsRegistry[nativeId] as? RNPlayerView {
              playerView.enableCustomUI()
            }
          }
          self?.players[nativeId] = PlayerFactory.create(playerConfig: playerConfig)
      }
   }
}
```

That should be it.

And there are other issues with your code too, but as I said, It'd be better to guide you in a PR.

**Comment by jonathanm-tkf** [comment] 2022-08-11 21:38
Thank you very much @pogist  for the comment, we are to help as soon as I can create a PR in draft mode and we will work together if you wish, as I said I am not a native developer but if I would like to meet the standards and/or requirements I need for my implementation due to requirements of my client, that's the magic of free software and mutual collaboration, thank you very much

**Comment by dweinber** [comment] 2023-02-16 09:32
Hi @jonathanm-tkf,
Thanks for your effort! Custom HTML UI support was added recently in https://github.com/bitmovin/bitmovin-player-react-native/pull/45 and https://github.com/bitmovin/bitmovin-player-react-native/pull/72. I believe we can close this issue, feel free to reopen if you believe there is still something left.

**Closed by dweinber** 2023-02-16 09:32 UTC
Labels: feature

**Comment by jonathanm-tkf** [comment] 2023-02-16 17:06
Thanks @dweinber thanks for your support
